##아래는 디폴트 설정입니다.

spring:
  profiles:
    active: dev #개발 설정은 dev, 운영 설정은 release
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace


##아래는 개발 설정입니다.
---
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    generate-unique-name: false
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  ##아래는 운영 설정입니다
---
spring:
  config:
    activate:
      on-profile: release
