##아래는 디폴트 설정입니다.

spring:
  profiles:
    active: dev #개발 설정은 dev, 운영 설정은 release
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
server:
  servlet:
    session:
      tracking-modes: cookie
